### ISSUE TITLE
Classe MainJoueur

### ISSUE THREAD

**Issue by victorlevasseur** [victorlevasseur/Jeu-du-menhir#6]
- [x] **V1 : Structure de la classe (référence vers Joueur et Manche).** Dépendances : #1(V1), #3(V1)
- [x] **V2 : Constructeur permettant d'ajouter MainJoueur comme référence dans Joueur et Manche automatiquement.** Dépendances : #1(V2), #3(V2)
- [x] **V3 : Stockage des cartes du joueur.** Dépendances : #7(V1), #8(V1), #9(V1)
- [x] **V4 : Stockage du nombre de graines et de menhir, ainsi que de la "défense" des chiens de garde".** : Dépendances : Aucune
- [x] **V5 : Défense du chien de garde :** Dépendances : Aucunes
