### ISSUE TITLE
Classe CarteIngredient

### ISSUE THREAD

**Issue by victorlevasseur** [victorlevasseur/Jeu-du-menhir#7]
- [x] **V1 : Structure de la classe et attributs.** Dépendances : Aucunes
- [x] **V2 : Structure de la méthode agir.** Dépendance : #3(V1), #6(V1)
- [x] **V3 : Contenu de la méthode agir.** Dépendance : #3(All), #6(All)
- [ ] **V4 : Instanciation des cartes.** Dépendance : #9
